name: synth-cargo-test

on:
  push:
    branches: [master]
    paths: ["**/*.rs"]
  pull_request:
    branches: [master]
    paths: ["**/*.rs"]

  workflow_dispatch:

jobs:
  cargo_test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Download brr
        env:
          TAG: 0.0.21
        run: |
          curl -L https://github.com/buildrecall/brr/releases/download/$TAG/brr-$TAG-x86_64-unknown-linux-musl -o /tmp/brr
          sudo mv /tmp/brr /usr/bin/brr
          sudo chmod +x /usr/bin/brr
          brr -V
      - if: matrix.os == 'ubuntu-latest'
        env:
          BUILDRECALL_API_KEY: ${{ secrets.BUILDRECALL_API_KEY }}
        run: brr run test linux
      - if: matrix.os == 'windows-latest'
        env:
          BUILDRECALL_API_KEY: ${{ secrets.BUILDRECALL_API_KEY }}
        run: brr run test-windows windows-cross
  clippy_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download brr
        env:
          TAG: 0.0.21
        run: |
          curl -L https://github.com/buildrecall/brr/releases/download/$TAG/brr-$TAG-x86_64-unknown-linux-musl -o /tmp/brr
          sudo mv /tmp/brr /usr/bin/brr
          sudo chmod +x /usr/bin/brr
          brr -V
      - run: brr run clippy linux
        env:
          BUILDRECALL_API_KEY: ${{ secrets.BUILDRECALL_API_KEY }}
  fmt_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download brr
        env:
          TAG: 0.0.21
        run: |
          curl -L https://github.com/buildrecall/brr/releases/download/$TAG/brr-$TAG-x86_64-unknown-linux-musl -o /tmp/brr
          sudo mv /tmp/brr /usr/bin/brr
          sudo chmod +x /usr/bin/brr
          brr -V
      - run: brr run fmt linux
        env:
          BUILDRECALL_API_KEY: ${{ secrets.BUILDRECALL_API_KEY }}
