name: synth ci/cd

on:
  pull_request:
    branches:
      - master

env:
  RUSTFLAGS: "-D warnings"

jobs:
  tests:
    name: synth tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Download brr
        env:
          TAG: 0.0.21
        run: |
          curl -L https://github.com/buildrecall/brr/releases/download/$TAG/brr-$TAG-x86_64-unknown-linux-musl -o /tmp/brr
          sudo mv /tmp/brr /usr/bin/brr
          sudo chmod +x /usr/bin/brr
          brr -V
      - run: brr run test linux
        env:
          BUILDRECALL_API_KEY: ${{ secrets.BUILDRECALL_API_KEY }}
